version: '3.7'

services:
  ts-node-docker:
    build:
      context: ./
      dockerfile: Dockerfile
      target: development-build-stage
    volumes:
      - ./:/app
      - /app/node_modules
    container_name: ts-node-docker
    restart: 'unless-stopped'
    ports:
      - '8000:8000'
    # networks:
    #   - backend
    # depends_on:
    #   - postgresql
    environment:
      - DATABASE_URL=${DATABASE_URL}
  # postgresql:
  #   platform: linux/amd64
  #   image: 'amd64/postgres:latest'
  #   build: .
  #   container_name: postgresql
  #   restart: 'unless-stopped'
  #   ports:
  #     - '5432:5432'
  #   environment:
  #     - POSTGRES_USER=parthmangrola
  #     - POSTGRES_PASSWORD=password
  #     - POSTGRES_DB=impress
  #   networks:
  #     - backend
  #   volumes:
  #     - data:/var/lib/postgresql/data
  # webserver:
  #   image: 'nginx:1.19.10-alpine'
  #   container_name: webserver
  #   restart: unless-stopped
  #   ports:
  #     - '80:80'
  #   volumes:
  #     - ./nginx-conf:/etc/nginx/conf.d
  #   depends_on:
  #     - ts-node-docker
  # networks:
  #   - backend
# networks:
#   backend:
#     driver: bridge

# volumes:
#   data:
#     driver: local
