-- AlterTable
ALTER TABLE "Film" ALTER COLUMN "name" DROP DEFAULT;

-- AlterTable
ALTER TABLE "Lube" ALTER COLUMN "name" DROP DEFAULT;

-- AlterTable
ALTER TABLE "Post" ALTER COLUMN "filmId" DROP DEFAULT,
ALTER COLUMN "lubeId" DROP DEFAULT,
ALTER COLUMN "typeId" DROP DEFAULT;

-- AlterTable
ALTER TABLE "Type" ALTER COLUMN "name" DROP DEFAULT;
